project:
  name: iotquickstart
  regions:
  - us-east-1
tests:
  default:
    parameters:
      ProjectName: 'iotquickstart'
      CACertificateID: 'abcd'
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3KeyPrefix: "iotquickstart"
    template: ./templates/main.template.yaml