# global:
#   owner: quickstart@amazon.com
#   qsname: quickstart-iot-connectivity-security
#   package_lambda: false
#   regions:
#     # - ap-northeast-1
#     # - ap-northeast-2
#     # - ap-south-1
#     # - ap-southeast-1
#     # - ap-southeast-2
#     # - ca-central-1
#     # - eu-central-1
#     # - eu-west-1
#     # - eu-west-2
#     # - sa-east-1
#     - us-east-1
#     # - us-east-2
#     # - us-west-1
#     # - us-west-2
#   reporting: true
#   s3_bucket: ''
project:
  name: iotquickstart
  regions:
  - us-east-1
tests:
  default:
    parameters:
      ProjectName: 'Test'
      ProjectRepoUrl: 'https://dy7wmgjy2d81x.cloudfront.net/iotquick.zip'
      CACertificateID: 'abcd'
    template: ./templates/main.template.yaml