// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment

=== Verify the deployment

. Sign in to the AWS Management Console, and open the AWS IoT console.

. Choose *Manage*, *Thing Groups*. Verify that prebuilt thing groups appear, such as `iotquickstart-Active`, `iotquickstart-inactive`, and `iotquickstart-Quarantine`.

. Choose *Defend*, *Audit*, *Schedules*. Verify that a daily https://docs.aws.amazon.com/iot/latest/developerguide/device-defender-audit.html[audit^] appears, such as ‘dailyaudit-main’.

. Choose *Defend*, *Detect*, *Security Profiles*. Verify that you an https://docs.aws.amazon.com/iot/latest/developerguide/dd-detect-ml.html[ML Detect^] Security Profile appears, for example ‘SecurityProfile-152920-main’. This confirms that device behavior is being monitored continuously.

=== Verify the device just-in-time registration process

. Connect one device https://docs.aws.amazon.com/iot/latest/developerguide/iot-connect-devices.html[with your account's AWS IoT data endpoint^].
+
When the device connects, the Quick Start performs a sequence of actions on the backend: 
+
* Generates an AWS IoT thing named with the common name (serial number) in the provided device certificate.
* Attaches the device certificate to the created IoT thing.
* Creates an AWS DynamoDB entry with the same Common Name for the device.
* Adds the IoT thing to the `iotquickstart-inactive` group with limited permissions.
* Activates the device certificate.

. Open the AWS IoT console, and choose *Manage*, *Things*. 

. Verify the IoT thing, its device certificate, and its group affiliation. You can identify the thing by its certificate common name, serial number, and thing name.

=== Verify the end-user device registration process

. Sign in to the AWS Management Console, and open the AWS Amplify console.  

. Under *All apps*, choose the *iotquickstart* app.

. Under the *Frontend environments* tab, choose the app image thumbnail. A new browser tab opens with a sign-up page.

. Create an account.

. Log in with the created account credentials. A *Register Device* page appears.
+
//TODO Tony, FYI, I've deleted the two screenshots from this section (and from the repo). Best practices from the AWS Style Guide: "Avoid using screenshots to show the results of a step that presumably the user sees on screen anyway." "Be sparing in the use of screenshots, because they can be hard to maintain and localize."

. Enter the serial number of the device that was previously connected and registered in AWS IoT, and choose *REGISTER DEVICE*. A confirmation message appears indicating successful registration.

. In the left panel, choose *Devices*. Confirm that the registered device appears under *My Devices*.

== Post-deployment steps
//TODO Tony, Does it makes sense to have the testing section precede post-deployment steps in this doc? This paragraph below seems to assume that we've just now completed the deployment. Please review this whole file for logical order and nesting of sections.

When the Cloudformation stack is complete, note the value for *DefaultDomain* in the *Outputs* tab. 
The setup process will continue after the initial Cloudformation stack is complete. 
It takes ~10 min to set up the full app using AWS Amplify after the first Cloudformation stack is complete. To check on status, 
open the AWS Amplify console and select your app. Once the Quick Start is fully deployed, you can create an account with the *DefaultDomain* value to view the web portal. 
To set up a custom domain for the web app, see https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html[Set up custom domains^].

//TODO Tony, Please revise the above content into steps. Use period-space instead of numbers as I've been doing in the other procedures. Details on our wiki: https://w.amazon.com/bin/view/AWS_Quick_Starts/docs2_0#HNumberedsteps

//TODO Tony, FYI, since our docs no longer include screenshots showing "outputs after successful deployment," I've deleted that screenshot.

=== Migrate to production
After you verify that the Quick Start is deployed and functions as intended, consider customizing and load testing your deployment before migrating it to production as follows:

* Customize the prebuilt AWS Amplify application in AWS CodeCommit so that the app meets your business use cases.
* Onboard IoT devices at the expected device-connection rate of your operations so that you can validate the processing rate and scale of the deployment. See https://docs.aws.amazon.com/general/latest/gr/iot-core.html[AWS IoT Core endpoint and quota^] for service resource and API quotas.

When you are satisfied with the Quick Start's application customization and load testing, you can deploy the solution in production.

=== Clean up
. Open the AWS Amplify console, navigate to your application, and delete it.
. Open the AWS Cloudformation console, select the stacks you created as part of the Quick Start, and delete them.

//== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

//_Add any best practices for using the software._

=== Security
AWS Identity and Access Management (IAM) roles enable you to assign granular access policies and permissions to services and users in the AWS Cloud. This Quick Start creates IAM roles that grant the solution’s services, such as AWS Lambda functions, permissions to perform specific actions. Besides, you need to obtain the following access for your IAM role:

* To deploy this Quick Start, you should have admin access, such as AWS managed IAM policy AdministratorAccess. After initial deployment, commits to the CodeCommit repository created by this Quick Start will build or update the Cloud infrastructure.
* To have the ability to update the CodeCommit repository, you should have an IAM role with the AWSCodeCommitPowerUser managed policy attached at a minimum.

les. Then swap in our standard three-line README blurb from any recent guide, and change the link to our guide. In the future, you can automate this. See https://code.amazon.com/reviews/CR-46203393/revisions/1#/details.) 