== Test the deployment

=== Verify the deployment

. Sign in to the AWS Management Console, and open the AWS IoT console.

. Navigate to *Manage* > *Thing groups*. Verify that the *prebuilt thing* groups appear (for example, `iotquickstart-Active`, `iotquickstart-inactive`, and `iotquickstart-Quarantine`).

. Navigate to *Defend* > *Audit* > *Schedules*. Verify that a daily https://docs.aws.amazon.com/iot/latest/developerguide/device-defender-audit.html[audit^] appears (for example, `dailyaudit-main`).

. Navigate to *Defend* > *Detect* > *Security profiles*. Verify that an https://docs.aws.amazon.com/iot/latest/developerguide/dd-detect-ml.html[ML Detect^] Security Profile appears (for example, `SecurityProfile-152920-main`). This confirms that device behavior is monitored continuously.

=== Verify the device just-in-time registration process

. https://docs.aws.amazon.com/iot/latest/developerguide/iot-connect-devices.html[Connect devices to AWS IoT^].
+
When the device connects, the Quick Start performs the following actions on the backend: 
+
* Generates an AWS IoT device using the common name (serial number) from the device's certificate.
* Attaches the certificate to the IoT device.
* Creates an AWS DynamoDB entry using the common name.
* Adds the IoT device to the `iotquickstart-inactive` group with limited permissions.
* Activates the device certificate.
+
. Open the AWS IoT console, and navigate to *Manage* > *Things*. 
. Verify the IoT device's certificate and group affiliation. You can identify IoT devices by their certificate, common name, and serial number.

=== Verify the end-user device registration process

. Sign in to the AWS Management Console, and navigate to the AWS Amplify console.  
. Under *All apps*, choose the *iotquickstart* application.
. Under the *Frontend environments* tab, choose the application's thumbnail. A new browser tab opens with a sign-up page.
. Create an account.
. Log in with your account credentials. A *Register device* page appears.
. Enter your device's serial number, and choose *REGISTER DEVICE*. A confirmation message appears indicating successful registration.
. In the left-hand pane, choose *Devices*. Confirm that the registered device appears under *My Devices*.

== Postdeployment steps

. When the AWS CloudFormation stack completes, note the *DefaultDomain* value in the *Outputs* tab. The process uses AWS Amplify to set up your application, which takes about 10 minutes.
. To check the stack's status, navigate to the AWS Amplify console, and choose your application.
. To view the web portal after the Quick Start is fully deployed, create an account using the *DefaultDomain* value. To set up a custom domain for the web application, see https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html[Set up custom domains^].

=== Migrate to production
When the deployment functions as intended, customize and load test it before migrating it to a production environment:

* Use AWS CodeCommit to customize the web application so that it meets your business needs.
* Onboard your IoT devices at the expected device-connection rate so that you can validate the deployment's processing rate and scale. For resource and API quotas, see https://docs.aws.amazon.com/general/latest/gr/iot-core.html[AWS IoT Core endpoint and quota^].

When you finish customizing and load testing the application, deploy this Quick Start to your production environment.

=== Clean up
. Navigate to the AWS Amplify console, choose your application, and delete it.
. Navigate to the AWS CloudFormation console, choose the associated stacks, and delete them.

== Additional information

=== Device data
Registered and active IoT devices have permission to publish to dt/${thingName}/#. 
An IoT rule directs telemetry messages from this topic to a dynamodb telemetry table with primary key = customerId:thingName and sort key=Epoch timestamp. 
CustomerId is obtained from the thing attribute value for account and thingName is obtained from the topic.

=== CI/CD pipeline

This project creates:

* CodeCommit repo in your account that is initialized with contents from the /submodules folder in the Github repo
* CI/CD enabled Amplify app that is triggered by commits to the CodeCommit repo (each commit will deploy updates to the backend and front end resources in your account) 

== Security
AWS Identity and Access Management (IAM) roles enable you to assign granular access policies to services and users. This Quick Start creates IAM roles that grant permissions to the deployment's resources, such as AWS Lambda functions. Obtain the following IAM access for your role:

* To deploy this Quick Start, you must have administrator access with an applicable IAM policy, such as `AdministratorAccess`. After the initial deployment, changes to the AWS CodeCommit repository will build or update the cloud infrastructure.
* To update the AWS CodeCommit repository, at a minimum you must use an IAM role with an attached `AWSCodeCommitPowerUser` policy. 