// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading
You can validate that your Quick Start is deployed successfully, by logging onto the AWS IoT console to review the initial setup:

1. Navigate to *Manage*, select *Thing Groups* from the left navigation, you should see pre-built thing groups listed on the page, such as ‘iotquickstart-Active’, ‘iotquickstart-inactive’, and ‘iotquickstart-Quarantine’ group.
2. To check cloud-side IoT configurations against AWS security best practices, navigate to *Defend*, select *Audit*, then select *Schedules* from the left navigation, 
you should see a daily https://docs.aws.amazon.com/iot/latest/developerguide/device-defender-audit.html[audit^] created, such as ‘dailyaudit-main’.
3. To verify that device behavior is being monitored on a continuous basis, navigate to *Defend*, select *Detect*, 
then select *Security Profiles* from the left navigation, you should see an https://docs.aws.amazon.com/iot/latest/developerguide/dd-detect-ml.html[ML Detect^] 
Security Profile configured, for example ‘SecurityProfile-152920-main’.

Secondly, you can test the device Just-in-Time Registration process included in the Quick Start:

1. Have one device https://docs.aws.amazon.com/iot/latest/developerguide/iot-connect-devices.html[connect with your account’s AWS IoT data endpoint^]
2. Once the device connects, the Quick Start performs a sequence of actions on the backend: 
    ** Generates an AWS IoT thing named with the Common Name (serial number) in the provided device certificate
    ** Attaches the device certificate to the created IoT thing
    ** Creates an AWS DynamoDB entry with the same Common Name for the device
    ** Adds the IoT thing to the ‘iotquickstart-inactive’ group’ with limited permissions
    ** Activates the device certificate
3. Then you can verify the IoT thing, its device certificate and its group affiliation in the AWS IoT console by going to *Manage*, then *Things* from the left navigation. Once on this page you can identify the thing by it's certificate Common Name/serial number/thing name.

Finally, you can test the end user device registration process through the AWS Amplify web app included in the Quick Start:

1. Sign in to the AWS Management Console and open the AWS Amplify console.  
2. Under *All apps*, choose the *iotquickstart* app.
3. Under the *Frontend environments* tab, choose the app image thumbnail. A new browser tab opens with a sign-up page.
4. Create an account.
5. Log in with the created account credentials. A *Register Device* page appears.
//TODO Tony, FYI, I've deleted the two screenshots from this section (and from the repo). Best practices from the AWS Style Guide: "Avoid using screenshots to show the results of a step that presumably the user sees on screen anyway." "Be sparing in the use of screenshots, because they can be hard to maintain and localize."

. Enter the serial number of the device that was previously connected and registered in AWS IoT, and choose *REGISTER DEVICE*. A confirmation message appears indicating successful registration.
. In the left panel, choose *Devices*. Confirm that the registered device appears under *My Devices*.

== Post-deployment steps

When the Cloudformation stack is complete, note the value for *DefaultDomain* in the *Outputs* tab. 
The setup process will continue after the initial Cloudformation stack is complete. 
It takes ~10 min to set up the full app using AWS Amplify after the first Cloudformation stack is complete. To check on status, 
open the AWS Amplify console and select your app. Once the Quick Start is fully deployed, you can create an account with the *DefaultDomain* value to view the web portal. 
To set up a custom domain for the web app, see https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html[Set up custom domains^].

//TODO Tony, Please revise the above content so that people can follow it step-by-step. Also, does it makes sense to have the testing section preceding this, or does the testing section need to follow the post-deployment steps?

//TODO Tony, Since our docs no longer include screenshots showing "outputs after successful deployment," I've deleted that screenshot.

=== From testing to production workloads

//TODO Tony, I don't understand the above subhead. Please review this whole section for logical flow.

After you verify that the Quick Start is deployed and functions as intended, customize and load test your deployment as follows:

. Customize the prebuilt AWS Amplify application in AWS CodeCommit so that the app meets your business use cases.
. Onboard IoT devices at the expected device-connection rate of your operations so that you can validate the processing rate and scale of the deployment. See https://docs.aws.amazon.com/general/latest/gr/iot-core.html[AWS IoT Core endpoint and quota^] for service resource and API quotas.
+
//TODO Tony, I converted the step numbers here and elsewhere from "1, 2, 3" to asciidoc autonumbering (period followed by a space). If I missed any, please do the same. Details on our wiki: https://w.amazon.com/bin/view/AWS_Quick_Starts/docs2_0#HNumberedsteps

When you are satisfied with the Quick Start's application customization and load testing, you can deploy the solution in production.

=== Clean up
. Open the AWS Amplify console, navigate to your application, and delete it.
. Open the AWS Cloudformation console, select the stacks you created as part of the Quick Start, and delete them.

//== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

//_Add any best practices for using the software._

== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

AWS Identity and Access Management (IAM) roles enable you to assign granular access policies and permissions to services and users in the AWS Cloud. 
This Quick Start creates IAM roles that grant the solution’s services, such as AWS Lambda functions, permissions to perform specific actions.

To deploy this Quick Start, you should have admin access, such as AWS managed IAM policy AdministratorAccess. 
After initial deployment, commits to the CodeCommit repository created by this Quick Start will build or update the Cloud infrastructure. To have the ability to update the CodeCommit repository, 
you should have an IAM role with the AWSCodeCommitPowerUser managed policy attached at a minimum.

//TODO Tony, Does the README file have any content that isn’t already in the guide (re: deploy and teardown)? If so, move that content into the appropriate .adoc files. Then swap in our standard three-line README blurb from any recent guide, and change the link to our guide. In the future, you can automate this. See https://code.amazon.com/reviews/CR-46203393/revisions/1#/details.) 