=== Set up an account in the web application

As soon as the CloudFormation stack is complete and the web application has been deployed, set up an account in the web application as follows:

. While you're still in the CloudFormation console, under the *Outputs* tab, note the `DefaultDomain` value. 
. Open the https://console.aws.amazon.com/amplify/[AWS Amplify console^].
. Choose *All apps*, and then choose the web application (`iotquickstart`).
. Under the *Frontend environments* tab, choose the web application's thumbnail. A browser tab opens with a sign-up page.
. Create an account using the `DefaultDomain` value you noted in Step 1.
. (Optional) Customize the web application so that it meets your business needs. For example, you might change the application name, create a banner, or https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html[set up a custom domain^].

== Test the deployment

=== Review the initial AWS IoT setup

. Open the https://console.aws.amazon.com/iot/[AWS IoT console^].

. Confirm that the thing groups were deployed in AWS IoT Device Management. To do this, at the left choose *Manage*, *Thing groups*. Under *prebuilt thing*, verify that groups appear with names containing `Active`, `inactive`, and `Quarantine` (for example, `iotquickstart-Active`, `iotquickstart-inactive`, and `iotquickstart-Quarantine`).

. Confirm that a daily https://docs.aws.amazon.com/iot/latest/developerguide/device-defender-audit.html[audit^] was scheduled in AWS IoT Device Defender. To do this, choose *Defend*, *Audit*, *Schedules*. Verify that a file appears with a name containing `dailyaudit` (for example, `dailyaudit-main`). This audit checks the cloud-side device configurations against AWS security best practices.

. Confirm that a machine learning Detect (https://docs.aws.amazon.com/iot/latest/developerguide/dd-detect-ml.html[ML Detect^]) Security Profile was deployed. To do this, choose *Defend*, *Detect*, *Security profiles*. Verify that a file appears with a name containing `SecurityProfile` (for example, `SecurityProfile-152920-main`). The presence of this file tells you that device behavior is being monitored continuously.

=== Test the device-registration process 

To test the device-registration process, you do two things: connect a device to AWS IoT and then activate the device, as described in the following sections.

==== Connect a device to AWS IoT

. Connect any device with a JITR-ready certificate to your account's AWS IoT device data endpoint through AWS IoT Core. For details, see https://docs.aws.amazon.com/iot/latest/developerguide/iot-connect-devices.html[Connecting devices to AWS IoT^].
+
The JITR Lambda function registers the device certificate with AWS IoT by doing the following on the backend: 
+
* Generates an IoT thing in the device registry using the common name (serial number) from the device certificate.
* Attaches the certificate to the generated IoT thing.
* Creates an AWS DynamoDB entry using the common name.
* Adds the IoT thing to the `<iotquickstart>-inactive` group with limited permissions (where the bracketed text represents the web application's name).
* Activates the device certificate.

. Open the https://console.aws.amazon.com/iot/[AWS IoT console^].
. At the left, choose *Manage*, *Things*. Verify that the newly registered certificate's serial number (common name) and group affiliation appear.

For more information on the JITR process, see https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/[Just-in-Time Registration of Device Certificates on AWS IoT^].

==== Activate the device

Now that you've connected a device to AWS IoT, its certificate is registered and activated. However, the device itself (the IoT thing) is still inactive. To activate the device—which typically means to register it to the end user—use the web application as follows:

. Open the https://console.aws.amazon.com/amplify/[AWS Amplify console^].  
. At the left, choose *All apps*, and then choose the web application.
. Under the *Frontend environments* tab, choose the web application's thumbnail.
. Log in with your account credentials. The *Register Device* page appears.
. Enter the serial number (common name) of the IoT device, and choose *REGISTER DEVICE*.
. At the left, choose *Devices*. On the *My Devices* page, verify that the device appears.

== Postdeployment steps

=== Migrate to a production environment

If you launched the Quick Start into a development or test environment and want to migrate to a production environment, follow these steps:

. Customize the web application so that it meets your business needs. For example, you might change the application name, create a banner, or https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html[set up a custom domain^].

. Create and register device certificates at the expected rates so that you can validate the deployment's processing rate and scale. For more information, see https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot[AWS IoT Core service quotas^].

. Change quotas or update your resource configuration as needed for your production use case. 

=== Clean up your development or test environment

When you no longer need the resources deployed by this Quick Start, clean up your development or test environment as follows:

. Open the https://console.aws.amazon.com/amplify/[AWS Amplify console^], and delete the web application.
. Open the https://console.aws.amazon.com/cloudformation/[AWS CloudFormation console^], and delete the stacks associated with this Quick Start.