=== Set up an account in the web application

As soon as the CloudFormation stack is complete and the web application has been deployed, set up an account in the web application as follows:

. While you're still in the CloudFormation console, under the *Outputs* tab, note the `DefaultDomain` value. 
. Open the https://console.aws.amazon.com/amplify/[AWS Amplify console^].
. Choose *All apps*, and then choose the web application (`iotquickstart`).
. Under the *Frontend environments* tab, choose the web application's thumbnail. A browser tab opens with a sign-up page.
. Create an account using the `DefaultDomain` value you noted in Step 1.
. (Optional) Customize the web application so that it meets your business needs. For example, you might want to change the application name, create a banner, or https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html[set up a custom domain^].

== Test the deployment

=== Confirm that the AWS IoT files were deployed

. Open the https://console.aws.amazon.com/iot/[AWS IoT console^].
. Confirm that the thing groups were deployed. To do this, choose *Manage*, *Thing groups*. Under *prebuilt thing*, verify that groups appear with names containing `Active`, `inactive`, and `Quarantine` (for example, `iotquickstart-Active`, `iotquickstart-inactive`, and `iotquickstart-Quarantine`).

. Confirm that an AWS IoT Device Defender daily https://docs.aws.amazon.com/iot/latest/developerguide/device-defender-audit.html[audit^] was scheduled. To do this, choose *Defend*, *Audit*, *Schedules*. Verify that a file appears with a name containing `dailyaudit` (for example, `dailyaudit-main`).

. Confirm that an https://docs.aws.amazon.com/iot/latest/developerguide/dd-detect-ml.html[ML Detect^] Security Profile was deployed. To do this, choose *Defend*, *Detect*, *Security profiles*. Verify that a file appears with a name containing `SecurityProfile` (for example, `SecurityProfile-152920-main`).

=== Test the JITR process for device certificates

To confirm that the just-in-time registration (JITR) process works, connect a single device to AWS IoT, and confirm that its certificate is automatically registered. Follow these steps:

. Connect any device to AWS IoT. For details, see https://docs.aws.amazon.com/iot/latest/developerguide/iot-connect-devices.html[Connecting devices to AWS IoT^].
+
The JITR Lambda function registers the device certificate with AWS IoT by doing the following: 
+
* Generates a thing in the device registry using the common name (serial number) from the device certificate.
* Attaches the certificate to the thing name.
* Creates an AWS DynamoDB entry using the common name.
* Adds the thing to the `<iotquickstart>-inactive` group with limited permissions (where the bracketed text represents the web application's name).
* Registers (activates) the device certificate.

. Open the https://console.aws.amazon.com/iot/[AWS IoT console^].
. Choose *Manage*, *Things*. Look for the device's common name (serial number). Verify that the device's certificate and group affiliation appear.

For more information on the JITR process, see the blog post https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/[Just-in-Time Registration of Device Certificates on AWS IoT^].

=== Test the process of registering devices

To confirm that the device-registration process works, register (activate) the physical device whose certificate you registered in the previous section. Use the web application, as end users (the device purchasers) would. Follow these steps:

. Open the https://console.aws.amazon.com/amplify/[AWS Amplify console^].  
. Choose *All apps*, and then choose the web application.
. Under the *Frontend environments* tab, choose the web application's thumbnail.
. Log in with your account credentials. The *Register device* page appears.
. Enter the serial number of the IoT device, and choose *REGISTER DEVICE*. A message indicates that the device is now registered.
. At the left, choose *Devices*. Verify that the registered device appears under *My Devices*.

== Postdeployment steps

=== Migrate to a production environment

If you launched the Quick Start into a development or test environment and want to migrate to a production environment, follow these steps:

. (Optional) Customize the web application so that it meets your business needs. For example, you might want to change the application name, create a banner, or https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html[set up a custom domain^].

. Create and register your device certificates at the expected rates so that you can validate the deployment's processing rate and scale. For more information, see https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot[AWS IoT Core service quotas^]. 

. Change quotas or update your resource configuration as needed for your production use case. 

=== Clean up your development or test environment

When you no longer need the resources deployed by this Quick Start, clean up your development or test environment as follows:

. Open the https://console.aws.amazon.com/amplify/[AWS Amplify console^], and delete the web application.
. Open the https://console.aws.amazon.com/cloudformation/[AWS CloudFormation console^], and delete the stacks associated with this Quick Start.