// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

=== Launch the Quick Start

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

[cols=",]
|===
|http://qs_launch_link[Deploy {partner-product-name} into your AWS account^] 
|===

WARNING: This quickstart can only be deployed to regions within your account that do not have an existing IoT device defender Audit Configuration. 

WARNING: Also, this quickstart can only be deployed once per region per account.

Each deployment takes about {deployment_time} to complete.

. Choose one of the following options to launch the AWS CloudFormation template. For help with choosing an option, see link:#_deployment_options[deployment options] earlier in this guide.

[start=2]
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for {partner-product-name} will be built. The template is launched in the {default_deployment_region} Region by default.

[start=3]
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary.


* Parameter: CACertificateID, see instructions for creating a https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/[certificate authority^] and registering within AWS IoT.

When the Cloudformation stack is complete, note the value for "DefaultDomain" under "Outputs". 

This setup process will continue after the initial Cloudformation stack is complete and takes ~10 min to setup the full app using AWS Amplify even after the first Cloudformation stack is complete.

To check on status, login to the AWS Amplify console and select your app.

Once fully deployed, create an account with the "DefaultDomain" to view the web portal.

===Teardown

1. Navigate to your app within the AWS Amplify console and select to delete app.
2. Navigate to the Cloudformation stack that you created in the AWS Cloudformation console and select to delete stack.