=== Confirm your AWS account configuration

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For more information, see link:#_planning_the_deployment[Planning the deployment], earlier in this guide.
. Ensure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

=== Launch the Quick Start
Each deployment takes about {deployment_time} to complete. This automated process includes creating the CloudFormation stack (10 minutes) and then deploying the web application (10 minutes). 

Consider launching the Quick Start into a development or test environment before deploying a production workload. 

. Sign in to your AWS account, and https://fwd.aws/g6NQ3?[deploy the {partner-product-short-name} Quick Start^]. (https://fwd.aws/PePnP?[View the template^].)
. Check the AWS Region displayed in the upper-right corner of the navigation bar, and change it if necessary. The template launches in the {default_deployment_region} Region by default. For more information, see link:#_supported_aws_regions[Supported AWS Regions] earlier in this guide.
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template, and provide values for any parameters that require input. For all other parameters, review the default settings and customize them as necessary. When you finish reviewing and customizing the parameters, choose *Next*.