==== Prepare your AWS account

Confirm that your AWS account has the permissions required to create the resources listed in the link:#_resource_quotas[Resource quotas] section of this guide.

==== Create device certificates

Any device certificate (client certificate) issued by your certificate authority (CA) can be registered with AWS IoT. To create JITR-ready device certificates—device certificates that will be automatically registered and activated whenever you connect the devices to AWS IoT for the first time—follow these steps.

. If you don't already have one, https://docs.aws.amazon.com/iot/latest/developerguide/create-your-CA-cert.html[create a CA certificate^], and https://docs.aws.amazon.com/iot/latest/developerguide/register-CA-cert.html[register it^] with AWS IoT. 
. For each IoT device, https://docs.aws.amazon.com/iot/latest/developerguide/create-device-cert.html[create a client certificate using your CA certificate^]. Use the device's serial number for the common name.

//TODO Miles or Cathy, Do we need a step to configure the CA certificate to support automatic registration of the client certificates (as mentioned on this webpage: https://docs.aws.amazon.com/iot/latest/developerguide/auto-register-device-cert.html)?

//TODO Miles or Cathy, Do we need a final step for installing the device (client) certificates on the devices (as mentioned in the blog post below)?

For more information on the JITR process, see https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/[Just-in-Time Registration of Device Certificates on AWS IoT^].

==== Check your AWS Region

Within your chosen AWS Region, confirm the following: 

* This deployment does not already exist.
* An audit configuration for AWS IoT Device Defender does not already exist. 