/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "products-dev",
            "region": "us-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-west-2:b7e23f1a-cec5-409d-b523-61aad6ce885b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_b9oOtPBgh",
    "aws_user_pools_web_client_id": "79bonoe445022taing5dp24p67",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "restApi",
            "endpoint": "https://a9kudahawb.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_content_delivery_bucket": "iotquickstart-20210322192836-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://d3s73uiin7vlbp.cloudfront.net"
};


export default awsmobile;
